### ISSUE TITLE
Data yang dikirim dari aplikasi

### ISSUE THREAD

**Issue by didats** [pemiluAPI/pemiluAPI.github.io#1]
Data yang dikirim dari aplikasi yg pakai API-nya akan kemana? Apa janji dari developer API terkait masalah data yg terkirim?

**Comment by vanbungkring** [comment]
+1

**Comment by ferland** [comment]
+1

**Comment by tyohan** [comment]
API masih in development, harapannya akhir tahun ini sudah bisa diakses. Untuk akses write, kita ada rencana kesana cuma mungkin disesuaikan untuk kebutuhan. Jadi tergantung data apa yang akan dikirim, dan buat apa. Kalau memang untuk kebutuhan melengkapi database mungkin bisa kita akses write.

Ini janji yang dimaksud seperti apa ya Mas Didats?

**Comment by didats** [comment]
Oh yohan yang punya projek. 

Datanya tak pikir ada yang write, kalo cuma read ya berarti gak perlu janji apa-apa toh. Takutnya datanya akan dijual kemana gitu, karena kita gak tau siapa aja yang ada di belakang api pemilu ini.

**Comment by tyohan** [comment]
Bukan yang punya sih, lebih tepatnya ikut mendukung karena yang kayak gini penting buat developer dan ke negara kita juga. Nanti dalam beberapa minggu ke depan kita akan publish teamnya kok, jadi teman-teman bisa tau siapa yang buat dan untuk apa. :)
