### ISSUE TITLE
API Docs

### ISSUE THREAD

**Issue by lontongcorp** [pemiluAPI/pemiluAPI.github.io#2]
Bikin dokumentasi API yang lengkap dong.
Prefer apiary.io jika berkenan, cross-domain dan websocket support ya :-)

**Comment by tyohan** [comment]
Kita masih menyiapkan API-nya jadi nanti kalau API sudah siap, dokumentasi akan kita buat selengkap mungkin. Untuk teknisnya nanti kita lihat sesuai kebutuhan dari developer kok, jadi kalau tidak ada kendala ya cross domain dan websocket mungkin bisa kita support.

**Comment by lontongcorp** [comment]
Mantap!
Mo nanya nih kira2 data apa aja ya yang bakal disertakan di API ini?
Apa ada SSO users kaya pake oAuth gitu ga?

**Comment by tyohan** [comment]
Beberapa data yang udah fix diantaranya data kandidat dan partai. Daftar pemilih juga lagi in progress tapi data pemilih mungkin tidak akan dipublish secara detail karena keperluannya untuk pengecekan apakah pemilih terdaftar atau tidak. Data-data lain akan terus kita tambahkan ke depannya.

SSO users, oAuth untuk awal belum kita implementasikan karena untuk tahap awal masih sebatas menyediakan data terkait pemilu. Kedepannya kalau memang dibutuhkan pasti akan kita provide.

**Comment by lontongcorp** [comment]
Data kandidat dan partai menurut ku sih wajib.  
Sedangkan untuk data pemilih sendiri dengan memasukkan No. KTP dan lokasi (kecamatan hingga propinsi) tempat tinggal dan TPS terkait. Kalau memang tidak ada implementasi oAuth atau SSO-nya, mungkin API request dengan memasukkan no. KTP untuk melakukan validasi pemilih mungkin sudah cukup tanpa harus tau detail pemilih secara lengkap.

Thx response nya bos. Kasitau kalau sudah ready ya :)

**Comment by tyohan** [comment]
@lontongcorp Data udah bisa dicoba ya. Coba check di http://developer.pemiluapi.org
