### ISSUE TITLE
Is this API still active?

### ISSUE THREAD

**Issue by ykt** [pemiluAPI/pemiluAPI.github.io#4]
Where is the API Doc? I am really needing it, currently I have been scraping all KPU site for the sources.
Thanks, and love to make it Open :)

**Comment by tyohan** [comment]
@ykt yes it's active. You can register on http://developer.pemiluapi.org/ and find the docs on http://developer.pemiluapi.org/endpoints .

Let us know when you have an app that use our API. Will love to share it to others :)

**Comment by ykt** [comment]
Thanks, just create the API token. I will love to share with others. This API is really great, cant wait to consume it :) 
This what we need, Open Data.

**Comment by mataherry** [comment]
Hello, is API key request still available?
